### ISSUE TITLE
errors seen in logs [Razer Blade Stealth late 2016]

### ISSUE THREAD

**Issue by nickdesaulniers** [openrazer/openrazer#821]
### Distribution

Linux Mint 19.1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

polychromatic wont connect to daemon.

```
➜  ~ sudo apt install openrazer-meta
...
Loading new openrazer-driver-2.5.0 DKMS files...
Building for 5.0.0-rc5+
Building initial module for 5.0.0-rc5+
Error! Bad return status for module build on kernel: 5.0.0-rc5+ (x86_64)
Consult /var/lib/dkms/openrazer-driver/2.5.0/build/make.log for more information.
...
➜  ~ less /var/lib/dkms/openrazer-driver/2.5.0/build/make.log
...
  CC [M]  /var/lib/dkms/openrazer-driver/2.5.0/build/driver/razerkbd_driver.o
In file included from ./arch/x86/include/asm/cpufeature.h:5:0,
                 from ./arch/x86/include/asm/thread_info.h:53,
                 from ./include/linux/thread_info.h:38,
                 from ./arch/x86/include/asm/preempt.h:7,
                 from ./include/linux/preempt.h:78,
                 from ./include/linux/spinlock.h:51,
                 from ./include/linux/mmzone.h:8,
                 from ./include/linux/gfp.h:6,
                 from ./include/linux/slab.h:15,
                 from /var/lib/dkms/openrazer-driver/2.5.0/build/driver/razerkbd_driv
er.c:22:
./arch/x86/include/asm/processor.h: In function ‘load_cr3’:
./arch/x86/include/asm/processor.h:240:12: error: implicit declaration of function ‘_
_sme_pa’; did you mean ‘__sme_clr’? [-Werror=implicit-function-declaration]
  write_cr3(__sme_pa(pgdir));
            ^~~~~~~~
            __sme_clr
```

is this because I have a custom kernel installed?

**Comment by z3ntu** [comment]
This doesn't like a problem caused by OpenRazer. Have you tried upgrading to the latest stable version 5.0.7? This might have been a problem with the -rc5 version of 5.0.0
