### ISSUE TITLE
Daemon not responding

### ISSUE THREAD

**Issue by mriel** [openrazer/openrazer#2603]
### Affected Device / PID

Blade 15 (2022) - RZ09-0421

### Operating System / Version

CachyOS KDE Plasma 6.5.2

### Kernel Version

6.17.7-3-cachyos (64-bit)

### OpenRazer Version

3.11.0

### Support Checklist

- [x] My user was added to the plugdev group.
- [x] I have rebooted and the problem persists.
- [x] I looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page and it did not solve the problem.

### Symptoms

- [ ] Uninstalling OpenRazer fixes the problem.
- [ ] Re-plugging the device fixes the problem.
- [ ] It worked before a system/kernel update.
- [ ] Only a problem if the daemon is running.
- [ ] Only a problem from power up or a reboot.
- [ ] Dual boot with Windows (Synapse not installed).
- [ ] Dual boot with Windows (Synapse 3 installed).
- [ ] Dual boot with Windows (Synapse 4 installed).
- [ ] Intermittent or erratic problem.
- [ ] My device is missing a feature.

### Please describe the issue

I've followed the troubleshooting steps and it looks like I have everything installed correctly. It does look like its the same issue as [#1733](https://github.com/openrazer/openrazer/issues/1733) and [#1652](https://github.com/openrazer/openrazer/issues/1652). I tried to do the same solution but removing persistance.conf did not fix the issue. 

Here is my output when using `openrazer-daemon -Fv`:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/daemonize.py", line 248, in start
    self.action(*privileged_action_result)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/openrazer-daemon", line 141, in run_daemon
    daemon = RazerDaemon(verbose=args.verbose,
                         log_dir=args.log_dir,
    ...<2 lines>...
                         persistence_file=args.persistence,
                         test_dir=args.test_dir)
  File "/usr/lib/python3.13/site-packages/openrazer_daemon/daemon.py", line 120, in __init__
    self._load_devices(first_run=True)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/openrazer_daemon/daemon.py", line 495, in _load_devices
    razer_device = device_class(device_path=sys_path, device_number=device_number, config=self._config,
                                persistence=self._persistence, testing=self._test_dir is not None,
                                additional_interfaces=sorted(additional_interfaces),
                                additional_methods=[],
                                unknown_serial_counter=self._unknown_serial_counter)
  File "/usr/lib/python3.13/site-packages/openrazer_daemon/hardware/keyboards.py", line 48, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/openrazer_daemon/hardware/keyboards.py", line 29, in __init__
    self.key_manager = _KeyboardKeyManager(self._device_number, self.event_files, self, use_epoll=True, testing=self._testing)
                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/openrazer_daemon/misc/key_event_management.py", line 243, in __init__
    self._keywatcher = KeyWatcher(device_id, event_files, self, use_epoll=use_epoll)
                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/openrazer_daemon/misc/key_event_management.py", line 118, in __init__
    self.open_event_files = [open(event_file, 'rb') for event_file in self._event_files]
                             ~~~~^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/input/by-id/usb-Razer_Razer_Blade-if01-event-kbd'

Stopping daemon.
Exception ignored in atexit callback <bound method Daemonize.exit of <daemonize.Daemonize object at 0x7fbd6000fcb0>>:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/daemonize.py", line 72, in exit
    sys.exit(0)
SystemExit: 0

Appreciate any help in the right direction.

[persistence.conf.zip](https://github.com/user-attachments/files/23426620/persistence.conf.zip)

**Comment by Mad-Professor** [comment]
I too have the same problem, after updating to 3.11.
It is complaining that I am not a member of openrazer, after adding myself to openrazer group, It still complains.

`025-11-12 14:45:16 | razer                          | CRITICAL | User is not a member of the openrazer group
2025-11-12 14:45:16 | razer                          | CRITICAL | Please run the command 'sudo gpasswd -a $USER openrazer' and then reboot!
Stopping daemon.
Exception ignored in atexit callback <bound method Daemonize.exit of <daemonize.Daemonize object at 0x78af8d11fcb0>>:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/daemonize.py", line 72, in exit
    sys.exit(0)
`

I'm running endeavourOS running lts kernel 6.12.57-1-lts
With a Razer Basilisk V3 1532:0099

Update: I've downgraded to 3.10.2, seems to be working. 
so 3.11 is broken on endeavourOS and maybe Arch.

Update2:
This seems to be related
https://github.com/openrazer/openrazer/issues/2601

**Comment by z3ntu** [comment]
Is this still an issue? After adding your user to the group printed and rebooting it should work again.

**Comment by Mad-Professor** [comment]
> Is this still an issue? After adding your user to the group printed and rebooting it should work again.

The new udev patch written by https://github.com/christophehenry seems to have helped.
Refer to here.
 https://github.com/openrazer/openrazer/pull/2643

Now I got a new issue. When the system resumes from sleep, the lighting on the mouse defaults to an off state, so I'm looking to see if someone has posted a bug report for it before creating a new report.

**Comment by mriel** [comment]
> Is this still an issue? After adding your user to the group printed and rebooting it should work again.

I don't think this is an issue anymore. All the checks were working but my laptop wasn't recognized as a supported device.
